import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./Components/Navbar/Navbar";
import Footer from "./Components/Footer/Footer";
import ShopByCategory from "./Components/Category/ShopByCategory";
import NextAuthProvider from "@/Providers/NextAuthProvider";
import { Toaster } from "react-hot-toast";

const geist = Geist({
  subsets: ["Playwrite NO"],
})
export const metadata = {
  title: "Top Cart",
  description: "Generated by create next app",
  icons: {
    icon: [
      { url: '/topcart.png', type: 'image/png' }
    ],
  }
};

export default function RootLayout({ children }) {

  return (
    <html lang="en" data-theme="light">
      <body
        className={`  antialiased`}>
        <NextAuthProvider>
          <Navbar></Navbar> 
          {children}
          <Toaster /> 
          <Footer></Footer> 
        </NextAuthProvider>
      </body>
    </html>
  );
}
