import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./Components/Navbar/Navbar";
import Footer from "./Components/Footer/Footer";
import ShopByCategory from "./Components/Category/ShopByCategory";

const geist = Geist({
  subsets: ["Playwrite NO"],
})
export const metadata = {
  title: "Top Cart",
  description: "Generated by create next app",
  icons: {
    icon: [
      { url: '/topcart.png', type: 'image/png' }
    ],
  }
};

export default function RootLayout({ children }) {
  
  return (
    <html lang="en" data-theme="light"  >
      <body
        className={`  antialiased`}>
        <Navbar></Navbar>
       
        {children}
        <Footer></Footer>

      </body>
    </html>
  );
}
